<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../SteelTree.GeoAcre/SteelTree.GeoAcre.csproj" />
    <ProjectReference Include="../SteelTree.GeoAcre.Ocr.AzureDocumentIntelligence/SteelTree.GeoAcre.Ocr.AzureDocumentIntelligence.csproj" />
  </ItemGroup>

</Project>
