<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../SteelTree.GeoAcre.Geometry/SteelTree.GeoAcre.Geometry.csproj" />
    <ProjectReference Include="../SteelTree.GeoAcre.Geocoding/SteelTree.GeoAcre.Geocoding.csproj" />
    <ProjectReference Include="../SteelTree.Ocr/SteelTree.Ocr.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
  </ItemGroup>

</Project>
